import { Box, Heading, VStack, Text, Button, useToast } from '@chakra-ui/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useState } from 'react'
import { useGlobalState } from '../state';
import { PersonData } from '../types';
import format from 'date-fns/format'


function AdminPage() {
	const [people, setPeople] = useState<(PersonData&{address: string}) []>([]);
	const [peopleCount, setPeopleCount] = useState<number | null>(null);
	const {drizzle, isAdmin} = useGlobalState();
	const router = useRouter();
	const toast = useToast()

	const fetchData = async () => {
		const peopleCount = await drizzle.contracts.Validator.methods.peopleCount().call()
		setPeopleCount(peopleCount)
		let promisedAddresses = []
		for (let i = 0; i < peopleCount; i++) {
			promisedAddresses.push(drizzle.contracts.Validator.methods.peopleAddress(peopleCount).call());
		}
		const addresses = await Promise.all(promisedAddresses)
		const promisedPeople = addresses.map(address => drizzle.contracts.Validator.methods.people(address).call());
		const promisedDetails = addresses.map(address => drizzle.contracts.Validator.methods.peopleDetails(address).call());
		const people = await Promise.all(promisedPeople);
		const details = await Promise.all(promisedDetails);
		const data = people.map((people, i) => ({...people, ...details[i], address: addresses[i]}))
		setPeople(data);
	}

	const verifyPerson = async (address: string) => {
		await drizzle.contracts.Validator.methods.verifyPerson(address).send();
		toast({
			title: "Person Verified",
			description: "We have verified the person.",
			status: "success",
			duration: 9000,
			isClosable: true,
		})
	}
	
	React.useEffect(() => {
		if (!isAdmin) {
      router.push('/');
			return;
		}
		fetchData();
	}, []);

	return (
		<>
			<Head>
        <title>Dashboard | Crypto Validator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
		<Box maxW="1400px" w="90%" m="0 auto">
			<Heading>Dashboard: Total Entries - {peopleCount}</Heading>
			<VStack spacing={4} mt={8}>
				{
					people.map((data) => 
						<Box w="100%" bg="gray.100" p={4} borderRadius="sm" key={data.firstName}>
							<Heading size="sm">{data.firstName} {data.lastName}</Heading>
							<Text>Email - {data.email}</Text>
							<Text>Education - {data.educationQualification}</Text>	
							<Text>Income - {data.income}</Text>	
							<Text>Date of Birth - {data.dob}</Text>
							<Button onClick={() => verifyPerson(data.address)} colorScheme="blue">Verify</Button>
						</Box>
					)
				}
			</VStack>
		</Box>
		</>
	)
}

export default AdminPage
