import { Container, Heading } from '@chakra-ui/layout'
import { Button } from '@chakra-ui/react'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useGlobalState } from '../state'
import Details from './../components/Details'

export default function Home() {
  const {drizzle,drizzleState, updateDetails} = useGlobalState() 
  const [data, setData] = useState<any>({})

  const fetchData = async () => {
    const address = drizzleState.accounts[0]
    const data  = await drizzle.contracts.Validator.methods.people(address).call()
    updateDetails(data)
    setData(data)
  }

  console.log(data)

  useEffect(() => {
    fetchData()
  }, [])
  return (
    <div>
      <Head>
        <title>Crypto Validator | Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <main>
          <Heading>Crypto Validator</Heading>
          {data.email ? <Details /> : 
          <Link href="/register">
            <Button width="100%" py={4} my={10} colorScheme="blue">
            Register
            </Button>
          </Link> 
          }
        </main>
      </Container>
      {/* <Container>
        <footer>
          <a
            href="/"
          >
            CryptoValidator
          </a>
        </footer>
      </Container> */}
    </div>
  )
}
