import { Container, Heading } from '@chakra-ui/layout'
import { Button } from '@chakra-ui/react'
import Head from 'next/head' 
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { useGlobalState } from '../state'
import { PersonData } from '../types'
import Details from './../components/Details'

export default function Home() {
  const {drizzle,drizzleState, updateDetails, updatePerson, makeAdmin} = useGlobalState() 
  const [data, setData] = useState<Partial<PersonData&{amount: string | number}>>({})
  const router = useRouter();

  const fetchData = async () => {
    const address = drizzleState.accounts[0]
    const person  = await drizzle.contracts.Validator.methods.people(address).call()
    const personDetails  = await drizzle.contracts.Validator.methods.peopleDetails(address).call()
    const isEligible  = await drizzle.contracts.Validator.methods.isEligible(address).call()
    console.log(person, personDetails)
    const isAdmin  = await drizzle.contracts.Validator.methods.isAdmin().call()
    if (isAdmin) {
      makeAdmin();
      router.push('/admin');
    } 
    updatePerson({...person, isEligible: !!isEligible})
    updateDetails(personDetails)
    setData({...person, ...personDetails, isEligible: !!isEligible, amount: isEligible});
  }


  useEffect(() => {
    fetchData()
  }, [])

  return (
    <div>
      <Head>
        <title>Crypto Validator | Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <main>
          <Heading>Crypto Validator</Heading>
          {data?.email ? <Details amount={data.amount} /> : 
          <Link href="/register">
            <Button width="100%" py={4} my={10} colorScheme="blue">
            Register
            </Button>
          </Link> 
          }
        </main>
      </Container>
      {/* <Container>
        <footer>
          <a
            href="/"
          >
            CryptoValidator
          </a>
        </footer>
      </Container> */}
    </div>
  )
}
